CREATE TABLE `t_statics_category_month` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增',
  `category_id` varchar(20) NOT NULL DEFAULT '' COMMENT '品类ID',
  `category_name` varchar(20) NOT NULL DEFAULT '' COMMENT '品类名称',
  `path` varchar(50) NOT NULL DEFAULT '' COMMENT '品类级别',
  `city_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '城市ID',
  `warehouse_id` varchar(255) NOT NULL DEFAULT '' COMMENT '仓库ID',
  `sale_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '总销售额',
  `actual_sale_amount` decimal(18,2) NOT NULL DEFAULT '0.00' COMMENT '实际销售额',
  `buy_amount` decimal(18,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '总采购成本',
  `sale_quantity` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '总销售件数',
  `online_sku_counts` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '在线SKU数',
  `sell_sku_counts` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '在时间周期内有销售的SKU数',
  `sku_total` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '该分类在SMS下所包含的SKU总数',
  `sale_sku_kinds_margin` float NOT NULL DEFAULT '0' COMMENT '整体动销率= sell_sku_counts/sku_total',
  `gross_margin` float NOT NULL DEFAULT '0' COMMENT '总毛利率',
  `order_users` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '时间周期内下单的客户总数',
  `sku_users` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '时间周期内购买过该SKU的客户总数',
  `order_cus_margin` float NOT NULL DEFAULT '0' COMMENT '客户覆盖率= sku_users/order_users',
  `sku_order_total` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '该分类下SKU的已完成订单总数',
  `complain_orders` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '投诉单数',
  `complaint_order_margin` float NOT NULL DEFAULT '0' COMMENT '质量问题投诉率= complain_orders/sku_order_total',
  `return_goods_orders` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '该分类下SKU的已处理退货退款单数',
  `return_order_margin` float NOT NULL DEFAULT '0' COMMENT '退货率= return_goods_orders/sku_order_total',
  `rejection_orders` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '该分类下SKU的订单拒收总件数',
  `out_stock_qty` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '该分类下SKU的销售出库总件数',
  `reject_sku_margin` float NOT NULL DEFAULT '0' COMMENT '拒收率= rejection_orders/out_stock_qty',
  `date_start` varchar(20) NOT NULL DEFAULT '0000-00-00' COMMENT '开始日期',
  `date_end` varchar(20) NOT NULL DEFAULT '0000-00-00' COMMENT '结束日期',
  `inhive_date` varchar(20) NOT NULL DEFAULT '0000-00-00' COMMENT '插入时间',
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`),
  KEY `date_start` (`date_start`),
  KEY `date_end` (`date_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 