CREATE TABLE `t_statics_sku_month` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `sku_number` int(10) NOT NULL DEFAULT '0' COMMENT '货号',
  `sku_name` varchar(64) NOT NULL DEFAULT '' COMMENT '名称',
  `sale_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '流水',
  `order_sku_counts` int(10) NOT NULL DEFAULT '0' COMMENT '订单中SKU数量',
  `order_counts` int(10) NOT NULL DEFAULT '0' COMMENT '已完成订单数量',
  `order_cus_counts` int(10) NOT NULL DEFAULT '0' COMMENT 'SKU下单顾客数',
  `total_order_cus_counts` int(10) NOT NULL DEFAULT '0' COMMENT '下单顾客数总数',
  `actual_sale_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实际销售额',
  `sale_quantity` int(10) NOT NULL DEFAULT '0' COMMENT '销售数量',
  `quantity_inwarehouse` int(10) NOT NULL DEFAULT '0' COMMENT '实时在库量',
  `quantity_salable` int(10) NOT NULL DEFAULT '0' COMMENT '实时可售量',
  `average_buy_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '平均采购价',
  `average_sale_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '平均销售价',
  `reject_sku_counts` int(10) NOT NULL DEFAULT '0' COMMENT '拒收sku数',
  `out_warehouse_sku_counts` int(10) NOT NULL DEFAULT '0' COMMENT 'sku出库销售总数',
  `complaint_order_counts` int(10) NOT NULL DEFAULT '0' COMMENT 'SKU的质量问题的投诉单数',
  `return_order_counts` int(10) NOT NULL DEFAULT '0' COMMENT 'SKU的已处理退货退款单数',
  `return_sku_counts` int(10) NOT NULL DEFAULT '0' COMMENT 'SKU的已处理退货件数',
  `warehouse_id` int(10) NOT NULL DEFAULT '0' COMMENT '仓库ID',
  `city_id` int(10) NOT NULL DEFAULT '0' COMMENT '城市ID',
  `unsalable_day_counts` int(10) NOT NULL DEFAULT '0' COMMENT '滞销天数',
  `margin_rate` float(6,4) NOT NULL DEFAULT '0.0000' COMMENT '毛利率',
  `cover_rate` float(5,4) NOT NULL DEFAULT '0.0000' COMMENT '客户覆盖率',
  `reject_rate` float(5,4) NOT NULL DEFAULT '0.0000' COMMENT '拒收率',
  `path` varchar(255) NOT NULL DEFAULT '' COMMENT '该SKU所对应的category所在的分类路径',
  `data_date` varchar(20) NOT NULL DEFAULT '0000-00-00' COMMENT '该条记录所指代的时间',
  `inhive_date` varchar(20) NOT NULL DEFAULT '0000-00-00' COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `sku_number` (`sku_number`),
  KEY `search_index` (`city_id`,`warehouse_id`,`data_date`,`path`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='统计静态化表';